nsl_date_var(transferDateParam, Format="%m/%d/%Y", Unique=YES, Refresh=SESSION);
nsl_search_var(authkey, PAGE=Login, LB/IC="\"base64EncodedAuthenticationKey\":\"", RB/IC="\"", LBMATCH=FIRST, ORD=1, SaveLen=0, ActionOnNotFound=Error, Search=Body, RETAINPREVALUE="NO", EncodeMode=All);
nsl_static_var(reliefFundClientIdParam:1,reliefFundSavingsIdParam:2, DATADIR=shared, File=relief_account_details.csv, Refresh=SESSION, Mode=SEQUENTIAL, EncodeMode=All);
nsl_static_var(userIdParam:1,savingsIdParam:2, DATADIR=shared, File=saving_account_details.csv, Refresh=SESSION, Mode=UNIQUE, EncodeMode=All, RemoveDupRecords=No);
nsl_static_var(reliefFundClientIdMtoMG1Param:1,reliefFundSavingIdMtoMG1Param:2, DATADIR=shared, File=relief_account_details_entries_G1.csv, Refresh=SESSION, Mode=SEQUENTIAL, EncodeMode=All);
nsl_decl_var(authToken,RETAINPREVALUE="NO");
nsl_decl_var(initialBalance,RETAINPREVALUE="NO");
nsl_decl_var(tenantId,DefaultValue="default",RETAINPREVALUE="NO");
nsl_decl_var(accountId,RETAINPREVALUE="NO");
nsl_decl_var(balanceBeforeTransfer,RETAINPREVALUE="NO");
