/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 05/11/2023 06:18:51
    Flow details:
    Build details: 4.11.0 (build# 47)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{

  ns_imap_list("ns-imap-list",
    "IMAP_SERVER=127.0.0.53", //replace with IMAP server IP
    "USER_ID=user1@cavisson.com",
    "PASSWORD=password",
  );

  ns_imap_fetch("ns-imap-fetch",
    "IMAP_SERVER=127.0.0.53", //replace with IMAP server IP
    "USER_ID=user1@cavisson.com",
    "PASSWORD=password",
    "MAIL_SEQ=1",
    "FETCH=HEADER"
  );

  ns_imap_select("ns-imap-select",
    "IMAP_SERVER=127.0.0.53", //replace with IMAP server IP
    "USER_ID=user1@cavisson.com",
    "PASSWORD=password"
  );

}
