/*-----------------------------------------------------------------------------
    Name: flow 
    Generated By: cavisson
    Date of generation: 07/24/26 09:40:06
    Flow details:
    Build details: 1.0.0
    Modification History:
-----------------------------------------------------------------------------*/ 
 

package TestJul_24_150441_Group_1;
import pacJnvmApi.NSApi;
import pacJnvmApi.NsFlow;

public class exit_script
{
  public static int execute(NSApi nsApi)
  {
    nsApi.ns_exit_rdt();
    return 0;
  }
}
