/*-----------------------------------------------------------------------------
    Name: flow 
    Generated By: cavisson
    Date of generation: 07/24/26 09:40:06
    Flow details:
    Build details: 1.0.0
    Modification History:
-----------------------------------------------------------------------------*/ 
 

package TestJul_24_150441_Group_1;
import pacJnvmApi.NSApi;
import pacJnvmApi.NsFlow;
import com.cavisson.rdt.conf.RDTTestConfig;
import com.cavisson.rdt.RDTMain;
import com.cavisson.rdt.RDTConstant;

public class init_script implements RDTConstant
{

  public static int execute(NSApi nsApi) throws Exception 
  { 
    RDTTestConfig  testConfig = RDTTestConfig.builder()
                              .mode(NATIVE)
                              .deviceType(MOBILE)
                              .testApp("{CAV_APP_URL}")
                              .build();
    testConfig.setWaitTimeOut(60);
    testConfig.setHeroEleWaitTimeout(60);     // init RDTSession instance and create driver according to test config
    nsApi.ns_init_rdt(testConfig);
    return 0;
  }
}
