/*-----------------------------------------------------------------------------
    Name: default_txn_10_10_70_138_8443
    Generated By: netstorm
    Date of generation: 08/12/2026 11:42:14
    Flow details:
    Build details: 4.15.2 (build# 32)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void default_txn_10_10_70_138_8443()
{
    ns_start_transaction ("default_txn_10_10_70_138_8443");
    ns_web_url ("default_txn_10_10_70_138_8443",
        "URL=https://10.10.70.138:8443/.*",
        "HEADER=Fineract-Platform-TenantId: default"
    );
    ns_end_transaction ("default_txn_10_10_70_138_8443", NS_AUTO_STATUS);

    ns_page_think_time(((double )ns_get_pg_think_time())/1000.0);
}
