/*-----------------------------------------------------------------------------
    Name: default_txn_127_0_0_1
    Generated By: netstorm
    Date of generation: 07/30/2026 06:40:08
    Flow details:
    Build details: 4.15.2 (build# 27)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void default_txn_127_0_0_1()
{
    ns_start_transaction ("default_txn_127_0_0_1");
    ns_web_url ("default_txn_127_0_0_1",
        "URL=http://127.0.0.1/.*"
    );
    ns_end_transaction ("default_txn_127_0_0_1", NS_AUTO_STATUS);

    ns_page_think_time(((double )ns_get_pg_think_time())/1000.0);

}
