/*-----------------------------------------------------------------------------
    Name: default_flow
    Generated By: netstorm
    Date of generation: 07/30/2026 06:40:08
    Flow details:
    Build details: 4.15.2 (build# 27)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void default_flow()
{
  int cav_replay_page_id = ns_get_int_val("cav_replay_page_id");
  //Default is called when page id is not valid. So log event.
  ns_log_event(EVENT_CRITICAL, "Replay default flow called for invalid page_id = %d", cav_replay_page_id);
  ns_page_think_time(0.1); 
}