nsl_json_var(dynamic_id, PAGE=index, OBJECT_PATH="root.id", ORD=1, SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=All);
nsl_decl_var(BASE_URL,DefaultValue="http://localhost:8080",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_title,DefaultValue="dynamic_post_title",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_dueDate,DefaultValue="dynamic_post_dueDate",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_completed,DefaultValue="dynamic_post_completed",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_id,DefaultValue="dynamic_id",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_put_title,DefaultValue="dynamic_put_title",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_put_dueDate,DefaultValue="dynamic_put_dueDate",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_put_completed,DefaultValue="dynamic_put_completed",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_put_invalid_id,DefaultValue="{dynamic_put_invalid_id}",RETAINPREVALUE="NO");
