/*-----------------------------------------------------------------------------
    Name: exit_script
    Generated By: sanjay
    Date of generation: 08/07/2023 06:15:40
    Flow details:
    Build details: 4.13.0 (build# 32)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int exit_script()
{
    return 0;
}
