/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: sanjay
    Date of generation: 08/07/2023 06:15:40
    Flow details:
    Build details: 4.13.0 (build# 32)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{
	//Login into LDAP server
	//Need to give User Is and password with the sevrer ip in the fornat : ldap://[userid]:[Password]@[server ip]:[port]
    ns_ldap_login("Login",
        "URL=ldap://UserId:Password@www.cavisson.com"
    );
    
   //Add entries
   //Give Distinguished Entry Name
    ns_ldap_add("Add",
        "URL=ldap://UserId:Password@www.cavisson.com",
        "DN=Distinguished entry name ex: cn=Peter Parker,ou=Accounting,DC=Fabricam,DC=com",
        ATTR_LIST_BEGIN,
            "NAME=Attribute Name, VALUE=Attribute Value",
        ATTR_LIST_END
    );
    
    //Delete a Entry
    ns_ldap_delete("Delete",
        "URL=ldap://UserId:Password@www.cavisson.com",
        "DN=cn=Peter Parker,ou=Accounting,DC=Fabricam,DC=com"
    );
    //Search any specific Entry
    ns_ldap_search("Search",
        "URL=ldap://UserId:Password@www.cavisson.com",
        "BASE=cn=Peter Parker,ou=Accounting,dc=Fabricam,dc=com",
        "SCOPE=Base",
        "FILTER=(ou)",
        "TIME_OUT=60",
        "MODE=SYNC"
    );

   //Modify any specific entries. User can add any new od delete and also modify useing the API.  
   ns_ldap_modify("Modify",
        "URL=ldap://UserId:Password@www.cavisson.com",
        "DN=cn=Peter Parker,ou=Accounting,dc=Fabricam,dc=com",
        ATTR_LIST_BEGIN,
            "OPERATION=MODIFY, ATTR_NAME=Attribute Name, VALUE=Attribute Value",
        ATTR_LIST_END
    ); 
    
   //Rename any Entry. User can alos Delete the oldone after renaming it.
   ns_ldap_rename("Rename",
        "URL=ldap://UserId:Password@www.cavisson.com",
        "DN=cn=Peter Parker,ou=Accounting,dc=Fabricam,dc=com",
        "NEW_RDN=cn=cn=miles morales,ou=Marketing,dc=Fabricam,dc=com",
        "DEL_OLD=1"
    );

   //To Logout from the Server. 
   ns_ldap_logout("Logout",
        "URL=ldap://UserId:Password@www.cavisson.com"
    );

}
