/*-----------------------------------------------------------------------------
    Name: flow 
    Generated By: yash
    Date of generation: 07/27/26 05:21:50
    Flow details:
    Build details: 1.0.0
    Modification History:
-----------------------------------------------------------------------------*/ 
 

package SMNG_Group_1;
import pacJnvmApi.NSApi;
import pacJnvmApi.NsFlow;

public class exit_script
{
  public static int execute(NSApi nsApi)
  {
    nsApi.ns_exit_rdt();
    return 0;
  }
}
