nsl_decl_var(BASE_URL,DefaultValue="http://localhost:8080",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_catalogBrandId,DefaultValue="dynamic_post_catalogBrandId",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_catalogTypeId,DefaultValue="dynamic_post_catalogTypeId",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_description,DefaultValue="dynamic_post_description",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_name,DefaultValue="dynamic_post_name",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_pictureUri,DefaultValue="dynamic_post_pictureUri",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_pictureBase64,DefaultValue="dynamic_post_pictureBase64",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_pictureName,DefaultValue="dynamic_post_pictureName",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_price,DefaultValue="dynamic_post_price",RETAINPREVALUE="NO");
