/*-----------------------------------------------------------------------------
      Name: exit_script
      Generated By: This is an auto generated script. You can, however, make a copy of this script using advanced script manager and enhance it.
      Date of generation: 06/29/2026 21:09:14
      Flow details:
      Build details: 4.15.0 build# 129
      Modification History:
      -----------------------------------------------------------------------------*/
  
      #include <stdio.h>
      #include <stdlib.h>
      #include <string.h>
      #include "ns_string.h"
  
      int exit_script()
      {
         return 0;
      }

