##To configure Central Respository, uncomment generatorServer, clientName, appName and provide values accordingly.
#generatorServer=https://184.105.48.40:4435
#clientName=Cavisson
#appName=QA
genCapacity=Medium
maxVuserCapacity=10
maxSessionRateCapacity=10
leaseDuration=1800
whiteListTest=0
#If whitelisttest=1 then whitelist is enable else false
thresholdPercentageForConsumedVuh=20

