nsl_decl_var(BASE_URL,DefaultValue="http://localhost:8080",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_buyerId,DefaultValue="dynamic_post_buyerId",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_item_id,DefaultValue="dynamic_post_item_id",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_productId,DefaultValue="dynamic_post_productId",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_productName,DefaultValue="dynamic_post_productName",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_unitPrice,DefaultValue="dynamic_post_unitPrice",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_oldUnitPrice,DefaultValue="dynamic_post_oldUnitPrice",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_quantity,DefaultValue="dynamic_post_quantity",RETAINPREVALUE="NO");
nsl_decl_var(dynamic_post_pictureUrl,DefaultValue="dynamic_post_pictureUrl",RETAINPREVALUE="NO");
