

URL /v1/sku/getitemavailability

nsl_search_var (SkuIdSP, LB="\"skuId\": \"", RB="\"", ORD=ALL, SaveOffset=0, SaveLen=0, Method=NONE, IgnoreCase=No, Search=BODY);
nsl_random_string_var (AvlStatus, Min=1, Max=1, CharSet=H,S,L, Refresh=USE);
nsl_static_var (Status, FILE=QualititaveStatus, REFRESH=USE, MODE=RANDOM, FirstDataLine=1, ColumnDelimiter=,, HeaderLine=0, IgnoreInvalidDataLine=NO);
ENABLE_DIRECT_ACCESS 1
RESPONSE_TEMPLATE GetAvaiabilityStatus Simulate NA service_GetAvaiabilityStatus.json active NA
TEMPLATE_BASED_COMPRESSION_TYPE GetAvaiabilityStatus none