/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 05/11/2023 05:19:30
    Flow details:
    Build details: 4.11.0 (build# 47)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow() 
{
  ns_start_transaction("Tx_DNS");
  ns_dns_query("get_hostbyName",
    "DNS_SERVER_IP=127.0.0.53", //replace with hostname and port of DNS server
    "TYPE=A",
    "ASSERT_RR_TYPE=A",
     "NAME=abc.default.com" //replace with a valid DNS resource name

  );
  ns_end_transaction("Tx_DNS", NS_AUTO_STATUS);


}
