URL /cav/samples/petstore 














nsl_query_var (QP_operation, QUERY=operation, ORD=1, METHOD=None);
HPD_DEBUG_TRACE 2
TEMPLATE_BASED_HEADER uploadFile Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
TEMPLATE_BASED_HEADER uploadFile Content-Disposition: form-data; name="file"; filename="Lebra.jpg"
TEMPLATE_BASED_HEADER uploadFile Content-Type: image/jpeg
nsl_date_var (DT_CurDate, Format="%m/%d/%Y", Offset=0, Refresh=SESSION);
nsl_decl_var (SCP_medium, DefaultValue="16");
nsl_search_var (SP_Username, LB=" \"username\": \"", RB="\",", ORD=ALL, SaveOffset=0, SaveLen=0, Method=NONE, IgnoreCase=No, Search=BODY);
nsl_random_number_var (RP_petId, Min=2, Max=9, Format=%04lu, Refresh=SESSION);
nsl_json_var(JP_Firstname, OBJECT_PATH="root.firstName", ORD=ALL, SaveOffset=0, Convert=None, EncodeMode=none);
nsl_json_var(JP_Password, OBJECT_PATH="root.password", ORD=ALL, SaveOffset=0, Convert=None, EncodeMode=none);
nsl_json_var(JP_Email, OBJECT_PATH="root.email", ORD=ALL, SaveOffset=0, Convert=None, EncodeMode=none);
nsl_json_var(JP_Lastname, OBJECT_PATH="root.lastName", ORD=ALL, SaveOffset=0, Convert=None, EncodeMode=none);
nsl_search_var (SP_ImgFileName, LB="&file=", RB="&", ORD=ALL, SaveOffset=0, SaveLen=0, Method=NONE, IgnoreCase=No, Search=BODY);
ENABLE_DIRECT_ACCESS 1
nsl_query_var (QP_PetsStatus, QUERY=PetsStatus, ORD=1, METHOD=None);
nsl_query_var (QP_PetTag, QUERY=PetTag, ORD=1, METHOD=None);
RESPONSE_TEMPLATE createUser Simulate NA service_createUser active QP_operation(String) = "createUser"
RESPONSE_TEMPLATE createUsersWithArrayInput Simulate NA service_createUsersWithArrayInput active QP_operation(String) = "createUsersWithArrayInput"
RESPONSE_TEMPLATE createUsersWithListInput Simulate NA service_createUsersWithListInput active QP_operation(String) = "createUsersWithListInput"
RESPONSE_TEMPLATE deleteUser Simulate NA service_deleteUser active QP_operation(String) = "deleteUser"
RESPONSE_TEMPLATE loginUser Simulate NA service_loginUser active QP_operation(String) = "loginUser"
RESPONSE_TEMPLATE addPet Simulate NA service_addPet active QP_operation(String) = "addPet"
RESPONSE_TEMPLATE updatePet Simulate NA service_updatePet active QP_operation(String) = "updatePet"
RESPONSE_TEMPLATE uploadFile Simulate NA service_uploadFile active QP_operation(String) = "uploadFile"
RESPONSE_TEMPLATE getInventory Simulate NA service_getInventory active QP_operation(String) = "getInventory"
RESPONSE_TEMPLATE getPetById Simulate NA service_getPetById active QP_operation(String) = "getPetById"
RESPONSE_TEMPLATE findPetsByStatus Simulate NA service_findPetsByStatus active QP_operation(String) = "findPetsByStatus" AND QP_PetsStatus(String) = "available"
RESPONSE_TEMPLATE findPetsByTags Simulate NA service_findPetsByTags active QP_operation(String) = "findPetsByTags" AND QP_PetTag(String) = "Cute"
RESPONSE_TEMPLATE findPetsByTags1 Simulate NA service_findPetsByTags1 active   QP_operation(String) = "findPetsByTags" AND QP_PetTag(String) = "Friendly"
RESPONSE_TEMPLATE placeOrder Simulate NA service_placeOrder active QP_operation(String) = "placeOrder"
RESPONSE_TEMPLATE logoutUser Simulate NA service_logoutUser active QP_operation(String) = "logoutUser"
