
URL /test

RESPONSE_TEMPLATE get_all_param Simulate NA service_get_all_param inactive NA
nsl_search_var (search_var, LB="name", RB="name", ORD=1, SaveOffset=0, SaveLen=0, Method=TRIM, IgnoreCase=No, Search=BODY);
nsl_decl_var (scratch_var, DefaultValue="testing");
nsl_decl_array (srratch_array, Size=5, DefaultValue="testing");
nsl_random_number_var (random_num, Min=1, Max=5, Format=%01lu, Refresh=USE);
nsl_random_string_var (random_string, Min=1, Max=10, CharSet=a-z, Refresh=USE);
nsl_unique_number_var (unique_num, Format=%01lu, Refresh=USE);
nsl_request_var (name, AssociatedObject="name", ORD="1", StartOffset="0", SaveLen="0", ActionOnNotFound="None", Method="None", Decode="No", DefaultValue="cavisson123", Encode="None");
nsl_xml_var (xml_var, NODE=<cav><data>, VALUE=<>, ORD=1, BodySkipStartBytes=0, BodySkipEndBytes=0);
RESPONSE_TEMPLATE get_xml Simulate NA service_get_xml active NA
