/*-----------------------------------------------------------------------------
    Name: flow 
    Generated By: yash
    Date of generation: 07/24/26 11:48:18
    Flow details:
    Build details: 1.0.0
    Modification History:
-----------------------------------------------------------------------------*/ 
 

package Snapify_iOS_T1_Group_1;
import pacJnvmApi.NSApi;
import pacJnvmApi.NsFlow;

public class exit_script
{
  public static int execute(NSApi nsApi)
  {
    nsApi.ns_exit_rdt();
    return 0;
  }
}
