/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 05/11/2023 05:45:13
    Flow details:
    Build details: 4.11.0 (build# 47)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{
    ns_start_transaction("Ftp_Get");
     ns_ftp_get("Get",
	   "FTP_SERVER=TestServer.cav-test.com:21", //replace with FTP server host and port
        "USER_ID=testuser", //replace ftp server userID
        "PASSWORD=testpass", //replace ftp server password
        "PASSIVE=Y",
        "FILE=ftp_tiny.txt"
        
    );
    ns_end_transaction("Ftp_Get", NS_AUTO_STATUS);
    ns_page_think_time(10.422);

     ns_start_transaction("Ftp_Put");
     ns_ftp_put("Put",
        "FTP_SERVER=TestServer.cav-test.com:21",
        "USER_ID=testuser",
        "PASSWORD=testpass",
        "PASSIVE=Y",
        "TYPE=I",
         "FILE=ftp_put.txt"
    );
    ns_end_transaction("Ftp_Put", NS_AUTO_STATUS);
    ns_page_think_time(10.422);


}