/*-----------------------------------------------------------------------------
    Name: Flow_1
    Generated By: This is an auto generated script. You can, however, make a copy of this script using advanced script manager and enhance it.
    Date of generation: 07/24/2026 10:41:17
    Flow details:
    Build details: 4.15.2 (build# 20)
    Modification History:
-----------------------------------------------------------------------------*/


/* Notes :
    There are few additional arguments in all click and script APIs which can be used based on the need:
    
    #NetworkIdleTimeout=<network_idle_timeout_ms>
    The network idle timeout, measured in milliseconds (ms), has a default value of 1500 ms. 
    If the onLoad event is triggered, and there is no network activity for this duration, the page will be considered as fully loaded. 
    It may be necessary to adjust this setting when the expected time gap between two calls exceeds the default value of 1500 ms.

    #PageLoadTimeout=<page_load_timeout_sec>
    This defines the maximum waiting time in seconds for a VUser (Virtual User) to wait for a page to load.
    If the page doesn't load within this duration, the page loading will be aborted, and any captured requests up to that point will be saved. 
    This feature is particularly useful when a specific page's load time exceeds the configured limit in the scenario. 
    The default value in the scenario is 60 seconds, which can be adjusted, but it will apply to all steps and pages.

    #VisualIdleTimeout=<visual_idle_timeout_ms>
    This parameter sets the visual idle timeout in milliseconds, with a default value of 1500 ms. After the network becomes idle, the VUser will wait for visual changes to stabilize.
    If there are no visual changes within this window of time after the network becomes idle, the page will be marked as visually complete. 
    This functionality proves valuable when a specific page's load time exceeds the configured limit in the scenario. 
    The default value in the scenario is 60 seconds, which can be adjusted, though it will apply to all steps and pages.

    #AuthCredential=<username>:<password>
    Provide authentication credentials in the format <username>:<password>. AuthCredential is used to supply authentication credentials for websites that require login. 
    The credentials (username and password) are passed in the first API request, either in ns_browser or ns_web_url.

    #Optional=<0 or 1>
    Optional is a flag used to prevent a specific transaction from affecting the rest of the transactions. 
    For instance, in cases involving popups, if the popup doesn't appear, the transaction could fail, disrupting the entire test. By setting Optional to 1, the test will continue even if the transaction fails.

    #heroElementID=<element id selector>
    #heroElementXPATH=<element xpath selector>	
    #heroElementXPATH1=<alternative element xpath selector>
    #heroElementCSSPATH=<csspath selector>	
    #heroElementDOMSTRING=<domstring>
    #heroElementMark=<value>
    #heroElementMeasure=<value>
    Visual progress is considered complete when the HeroElement becomes visible on the screen. Users can specify any element as the hero element using the above arguments.
-----------------------------------------------------------------------------*/
package TestJul_24_155643_Group_1;
import pacJnvmApi.NSApi;
import pacJnvmApi.NsFlow;

public class Flow_1 implements NsFlow
{
    public int execute(NSApi nsApi) throws Exception
    {
        int status = 0;

    // should_add_think_time will be updated in condition block of ns_web_url and call thinktime post-response code execution.
    int should_add_think_time = 0;
        nsApi.ns_start_transaction("LaunchApp");
        nsApi.ns_launch_app("LaunchApp"            ,
            "appPackage=com.cavisson.snapifyApp",
            "heroElementXPATH=//XCUIElementTypeStaticText[@name=\"Clothing\"]",
            "heroElementCLASS=XCUIElementTypeStaticText");
        nsApi.ns_end_transaction("LaunchApp", NS_AUTO_STATUS);
        nsApi.ns_page_think_time(0.000); 


        nsApi.ns_start_transaction("click_1");
        nsApi.ns_click("click_1"            ,
            "value=NA",
            "Snapshot=post_snapshot_1784888857359.png",
            "PreSnapshot=pre_snapshot_1784888857359.png",
            "PageSource=source_1784888857359.xml",
            "xpath=//XCUIElementTypeStaticText[@name=\"Clothing\"]",
            "class=XCUIElementTypeStaticText",
            "heroElementXPATH=//XCUIElementTypeButton[@name=\"Electronics\"]",
            "heroElementXPATH1=//*[@name='Electronics'][@label='Electronics']");
        nsApi.ns_end_transaction("click_1", NS_AUTO_STATUS);
        nsApi.ns_page_think_time(0.000); 


        nsApi.ns_start_transaction("click_2");
        nsApi.ns_click("click_2"            ,
            "value=NA",
            "Snapshot=post_snapshot_1784888908204.png",
            "PreSnapshot=pre_snapshot_1784888908204.png",
            "PageSource=source_1784888908204.xml",
            "xpath=//XCUIElementTypeButton[@name=\"Electronics\"]",
            "xpath1=//*[@name='Electronics'][@label='Electronics']",
            "heroElementXPATH=//XCUIElementTypeImage[@name=\"Wireless Headphones $199.99\"]",
            "heroElementACCESSIBILITYID=Wireless Headphones $199.99");
        nsApi.ns_end_transaction("click_2", NS_AUTO_STATUS);
        nsApi.ns_page_think_time(0.000); 


        nsApi.ns_start_transaction("click_3");
        nsApi.ns_click("click_3"            ,
            "value=NA",
            "Snapshot=post_snapshot_1784888918217.png",
            "PreSnapshot=pre_snapshot_1784888918217.png",
            "PageSource=source_1784888918217.xml",
            "xpath=//XCUIElementTypeImage[@name=\"Wireless Headphones $199.99\"]",
            "accessibilityId=Wireless Headphones $199.99");
        nsApi.ns_end_transaction("click_3", NS_AUTO_STATUS);
        nsApi.ns_page_think_time(0.000); 


        nsApi.ns_start_transaction("click_4");
        nsApi.ns_click("click_4"            ,
            "value=NA",
            "Snapshot=post_snapshot_1784889578481.png",
            "PreSnapshot=pre_snapshot_1784889578481.png",
            "PageSource=source_1784889578481.xml",
            "xpath=//XCUIElementTypeButton[@name=\"Clothing\"]",
            "xpath1=//*[@name='Clothing'][@label='Clothing']",
            "accessibilityId=Clothing",
            "heroElementXPATH=//XCUIElementTypeButton[@name=\"Orders Tab 4 of 5\"]",
            "heroElementACCESSIBILITYID=Orders Tab 4 of 5");
        nsApi.ns_end_transaction("click_4", NS_AUTO_STATUS);
        nsApi.ns_page_think_time(0.000); 


        nsApi.ns_start_transaction("click_5");
        nsApi.ns_click("click_5"            ,
            "value=NA",
            "Snapshot=post_snapshot_1784889593222.png",
            "PreSnapshot=pre_snapshot_1784889593222.png",
            "PageSource=source_1784889593222.xml",
            "xpath=//XCUIElementTypeButton[@name=\"Orders Tab 4 of 5\"]",
            "accessibilityId=Orders Tab 4 of 5",
            "heroElementXPATH=//XCUIElementTypeButton[@name=\"Home Tab 1 of 5\"]",
            "heroElementACCESSIBILITYID=Home Tab 1 of 5");
        nsApi.ns_end_transaction("click_5", NS_AUTO_STATUS);
        nsApi.ns_page_think_time(0.000); 


        nsApi.ns_start_transaction("click_6");
        nsApi.ns_click("click_6"            ,
            "value=NA",
            "Snapshot=post_snapshot_1784889612844.png",
            "PreSnapshot=pre_snapshot_1784889612844.png",
            "PageSource=source_1784889612844.xml",
            "xpath=//XCUIElementTypeButton[@name=\"Home Tab 1 of 5\"]",
            "accessibilityId=Home Tab 1 of 5",
            "heroElementXPATH=//XCUIElementTypeButton[@name=\"Home Tab 1 of 5\"]",
            "heroElementACCESSIBILITYID=Home Tab 1 of 5");
        nsApi.ns_end_transaction("click_6", NS_AUTO_STATUS);
        nsApi.ns_page_think_time(0.000); 


        nsApi.ns_start_transaction("click_7");
        nsApi.ns_click("click_7"            ,
            "value=NA",
            "Snapshot=post_snapshot_1784889626861.png",
            "PreSnapshot=pre_snapshot_1784889626861.png",
            "PageSource=source_1784889626861.xml",
            "xpath=//XCUIElementTypeButton[@name=\"Home Tab 1 of 5\"]",
            "accessibilityId=Home Tab 1 of 5");
        nsApi.ns_end_transaction("click_7", NS_AUTO_STATUS);
        nsApi.ns_page_think_time(0.000); 
    return status;
    }
}
